{{- if .Values.configMap.enabled }}
<<<<<<< HEAD
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMap.name }}-main-config"
  namespace: {{ .Release.Namespace }}
data:
    {{- range $key, $value := .Values.configMap.data }}
       {{ $key }}: "{{ $value }}"
    {{- end }}
{{- end }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMap.name }}-nginx-config"
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
{{ tpl (.Files.Get "config/default.conf") . | indent 4 }}
=======
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
>>>>>>> ddfe5f4 (good lord)
