---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
<<<<<<< HEAD
  namespace: {{ .Release.Namespace }}
=======
  namespace: {{ .Values.namespace }}
>>>>>>> ddfe5f4 (good lord)
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
<<<<<<< HEAD

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.awsSecretsManager.secretProviderClassName }}

      containers:
        - name: laravel-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true

          envFrom:
            - configMapRef:
                name: "{{ .Values.configMap.name }}-main-config"
            - secretRef:
                name: {{ .Values.awsSecretsManager.k8sSecretName }}


---
=======
      containers:
        - name: laravel-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}

---

# Frontend Deployment
>>>>>>> ddfe5f4 (good lord)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
<<<<<<< HEAD
  namespace: {{ .Release.Namespace }}
=======
  namespace: {{ .Values.namespace }}
>>>>>>> ddfe5f4 (good lord)
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: nginx-frontend
<<<<<<< HEAD
          image: nginx:1.25
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Values.configMap.name }}-nginx-config


=======
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: APP_URL
            - name: BACKEND_URL
              value: "$(APP_URL):{{ .Values.frontend.service.port }}"
>>>>>>> ddfe5f4 (good lord)
