{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gateway }}
  hostnames:
    - {{ .Values.httproute.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.frontend.name }}
          port: {{ .Values.frontend.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: {{ .Values.backend.name }}
          port: {{ .Values.backend.service.port }}
{{- end }}
