{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
<<<<<<< HEAD
  namespace: {{ .Release.Namespace }}
=======
  namespace: {{ .Values.namespace }}
>>>>>>> ddfe5f4 (good lord)
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
