{{/* Backend Service */}}
apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
=======
  name: {{ .Values.backend.name | default (printf "%s-backend-svc" .Release.Name) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
>>>>>>> ddfe5f4 (good lord)
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.service.port | default 80 }}
      targetPort: {{ .Values.backend.service.port | default 80 }}

<<<<<<< HEAD

=======
>>>>>>> ddfe5f4 (good lord)
---
{{/* Frontend Service */}}
apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
=======
  name: {{ .Values.frontend.name | default (printf "%s-frontend-svc" .Release.Name) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
>>>>>>> ddfe5f4 (good lord)
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.service.port | default 80 }}
      targetPort: {{ .Values.frontend.service.port | default 80 }}
<<<<<<< HEAD

      
=======
>>>>>>> ddfe5f4 (good lord)
