{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
<<<<<<< HEAD
  namespace: {{ .Release.Namespace }}
=======
  namespace: {{ .Values.namespace }}
>>>>>>> ddfe5f4 (good lord)
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
