{{- if not (lookup "v1" "Namespace" .Release.Namespace "" ) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "jjhealth.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
{{- end }}